import type { NextPage } from "next";

import {
	Box,
	Flex,
	Heading,
	Text,
	useBreakpointValue,
	useMediaQuery,
} from "@chakra-ui/react";
import Head from "next/head";
import mobile from "is-mobile";

const Home: NextPage = () => {
	const [isPortrait] = useMediaQuery("(orientation: portrait)");

	const isMobile = mobile();

	const bgURL = useBreakpointValue(
		{
			base: "/images/wave-haikei-small.svg",
			md: isPortrait
				? "/images/wave-haikei-small.svg"
				: "/images/wave-haikei-med.svg",
			xl: "/images/wave-haikei-large.svg",
		},
		isMobile ? "base" : "xl"
	);

	return (
		<Box bgImage={bgURL} bgSize="cover" h="100vh" zIndex="3">
			<Head>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Flex
				p="3rem"
				w="60vw"
				pt="10rem"
				flexDir="column"
				justifyContent="center"
			>
				<Heading color="white">
					Hello There! I am{" "}
					<Text as="span" color="blue.400">
						Sai Sridhar Akula
					</Text>
					, a Fullstack Developer
				</Heading>
			</Flex>
		</Box>
	);
};

export default Home;
